export const STRIPE_FRONT_KEY =
  "pk_test_51HTrdNKvlLDAjAUzb0c9zHwvq0wAcXOTWThrIscZMRVTc9xcfmqcFm4nLUjij9ZUcwgaewsQuNpBWak2KDQo1p4A00mFA5hRXA";
export const STRIPE_BACK_KEY =
  "sk_test_51HTrdNKvlLDAjAUzi8u2jGnHqF2SkxKmRG91jjcq70LxTeJcXeAuX9SuSeuzDQeegVeYrdfa9MBByfAELT0ylVyi00zOCmEdWL";
